# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPromenapodatka():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_promenapodatka(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1280, 693)
    self.driver.get("http://127.0.0.1:8000/login/")  # putanja do login strane
    self.driver.find_element(By.NAME, "email").send_keys("jovan@example.com")
    self.driver.find_element(By.NAME, "password").send_keys("lozinka123")
    self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    self.driver.find_element(By.LINK_TEXT, "Moj profil").click()
    self.driver.find_element(By.ID, "enableEditBtn").click()
    self.driver.find_element(By.NAME, "prezime").click()
    prezime_input = self.driver.find_element(By.NAME, "prezime")
    prezime_input.clear()  # briše postojeći tekst
    prezime_input.send_keys("Milvanovic")
    self.driver.find_element(By.CSS_SELECTOR, ".button:nth-child(9)").click()
    self.driver.find_element(By.CSS_SELECTOR, "#pacijent-view > div:nth-child(1)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#pacijent-view > div:nth-child(1)").text == "Ime: Jovan Milvanovic"
  
