# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMapapacijent():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_mapapacijent(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1280, 693)
    self.driver.get("http://127.0.0.1:8000/login/")  # putanja do login strane
    self.driver.find_element(By.NAME, "email").send_keys("jovan@example.com")
    self.driver.find_element(By.NAME, "password").send_keys("lozinka123")
    self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    self.driver.find_element(By.LINK_TEXT, "Pretraga").click()
    self.driver.execute_script("window.scrollTo(0,224)")
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(2) > .h1").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(2) > .h1").text == "Mapa"
    self.driver.close()
  
