# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPretragabezrezultata():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pretragabezrezultata(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1280, 693)
    self.driver.get("http://127.0.0.1:8000/login/")  # putanja do login strane
    self.driver.find_element(By.NAME, "email").send_keys("jovan@example.com")
    self.driver.find_element(By.NAME, "password").send_keys("lozinka123")
    self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    self.driver.find_element(By.LINK_TEXT, "Pretraga").click()
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.NAME, "q").send_keys("danilo")
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .button:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(1)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3)").text == "Nema rezultata za vašu pretragu."
  
