# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMapaguest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_mapaguest(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1280, 693)
    self.driver.find_element(By.LINK_TEXT, "Pretraga").click()
    self.driver.find_element(By.CSS_SELECTOR, ".small").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".small").text == "Morate biti ulogovani da biste imali funkcionalnosti mape."
    self.driver.close()
  
