# Generated by Django 5.2.7 on 2025-10-17 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doktor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='doctordocument',
            table='doctor_documents',
        ),
        migrations.AlterModelTable(
            name='klinike',
            table='klinike',
        ),
        migrations.AlterModelTable(
            name='lekari',
            table='lekari',
        ),
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='slika',
            table='slika',
        ),
        migrations.AlterModelTable(
            name='termini',
            table='termini',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.CreateModel(
            name='Aktuelnosti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=200)),
                ('sadrzaj', models.TextField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slika', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doktor.slika')),
            ],
            options={
                'db_table': 'aktuelnosti',
            },
        ),
        migrations.CreateModel(
            name='Poruke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField()),
                ('poslato', models.DateTimeField(auto_now_add=True)),
                ('posiljalac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('primalac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'poruke',
            },
        ),
        migrations.CreateModel(
            name='Recenzije',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('komentar', models.TextField(blank=True, null=True)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('lekar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doktor.lekari')),
                ('pacijent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recenzije',
            },
        ),
        migrations.CreateModel(
            name='Recepti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('tekst', models.TextField()),
                ('lekar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doktor.lekari')),
                ('pacijent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slika', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doktor.slika')),
            ],
            options={
                'db_table': 'recepti',
            },
        ),
        migrations.CreateModel(
            name='OmiljeniLekari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lekar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doktor.lekari')),
                ('pacijent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'omiljeni_lekari',
                'unique_together': {('pacijent', 'lekar')},
            },
        ),
    ]
