# Generated by Django 5.2.7 on 2025-10-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doktor', '0002_alter_user_options_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termini',
            name='status',
            field=models.CharField(choices=[('zakazan', 'Zakazan'), ('otkazan', 'Otkazan'), ('zavrsen', 'Završen'), ('potvrđen', 'Potvrđen')], default='slobodan', max_length=20),
        ),
    ]
