# Generated by Django 5.2.7 on 2025-10-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doktor', '0003_alter_termini_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slika',
            name='slika_link',
            field=models.ImageField(upload_to='slikeAktuelnosti/'),
        ),
    ]
