# Generated by Django 5.2.7 on 2025-10-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doktor', '0004_alter_slika_slika_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lekari',
            name='cena',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
