# Generated by Django 5.2.7 on 2025-10-25 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doktor', '0007_userdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='poruke',
            name='recept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doktor.recepti'),
        ),
        migrations.AlterField(
            model_name='poruke',
            name='tekst',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
