# Generated by Django 5.2.7 on 2025-10-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doktor', '0009_clinicdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktuelnosti',
            name='verifikovana',
            field=models.BooleanField(default=False),
        ),
    ]
