# Generated by Django 5.2.7 on 2025-10-26 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doktor', '0010_aktuelnosti_verifikovana'),
    ]

    operations = [
        migrations.AddField(
            model_name='termini',
            name='recept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doktor.recepti'),
        ),
    ]
