# Generated by Django 5.2.7 on 2025-10-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doktor', '0011_termini_recept'),
    ]

    operations = [
        migrations.AddField(
            model_name='termini',
            name='cena',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
